function [fitresult, gof] = createFit1(a)
%CREATEFIT(A)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: a
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Oct-2016 14:43:24


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], a );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
 legend( h, 'a', '666666666666666666666666untitled fit 1', 'Location', 'NorthEast' );
% Label axes
ylabel a
grid on


